### ISSUE TITLE
HAVE_MEMORY_SANITIZER and HAVE_ADDRESS_SANITIZER not set

### ISSUE THREAD

**Issue by smspillaz** [arsenm/sanitizers-cmake#2]
The documentation suggests that these should be set, but they are not when using FindASan and FindMSan.

**Comment by alehaa** [comment]
I think this bug might be fixed in the new released version. There are no ``HAVE_*_SANITIZER`` flags anymore, but compiler-dependend variables containing the sanitizer flags.

To get the behavior you like to have, you need the following code:
```CMake
add_executable(demo demo.c)
add_sanitize_address(demo)

if (DEFINED ${ASan_${CMAKE_C_COMPILER_ID}_FLAGS})
    message(STATUS "ASan enabled for target demo")
endif ()
```
